version: "3.5"
services:
  odpapi:
    container_name: odp-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8979:8999"
    environment:
      - CKAN_URL
    restart: always
