version: "3.5"
services:
  odp-api:
    container_name: odp-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - SERVER_ENV
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8888

      - ACCOUNTS_API_URL
      - OAUTH2_AUDIENCE=ODP-API

      - METADATA.ADAPTER=CKANAdapter
      - METADATA.OAUTH2_SCOPE=ODP.Metadata
      - METADATA.READONLY_ROLES
      - METADATA.READWRITE_ROLES
      - METADATA.ADMIN_ROLES

      - CKAN_ADAPTER.CKAN_URL
